language: python
python:
  - "3.8"
services:
  - postgresql
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  global:
    - APP_SETTINGS="config.TestingConfig"
    - SECRET_KEY="blah_blah_blah"
# command to run tests
script:
  - python -m pytest -v